type Order {
  orderID: Int
  customerID: String
  customer: Customer
  employeeID: Int
  employee: Employee
  orderDate: Date
  requiredDate: Date
  shippedDate: Date
  shipVia: Int
  freight: Float
  shipName: String
  shipAddress: Address
  details: [OrderDetails]! 
}

type OrderDetails {
  productID: Int
  product: Product
  unitPrice: Float
  quantity: Int
  discount: Float
}

extend type Query {
  order(id: ID!): Order
  orders(filter: OrderFilterInput, limit: Int! = 20, offset: Int): [Order]!
}

input OrderFilterInput {
  orderID: Int
  customerID: String
  employeeID: Int
  orderDate: Date
  requiredDate: Date
  shippedDate: Date
  shipVia: Int
  freight: Float
  shipName: String
  shipAddress: AddressInput
}
