type Article {
  # `aaa` | `ok` \\\
  title: String!
  desc: String
  createdAt: Int
  updatedAt: Int
}

type ArticleMutations {
  create: Float
  update: Float
  remove: Float
}

extend type Mutation {
  article: ArticleMutations
}